name: Build
on: [push, pull_request]

jobs:
  build:
    name: EfbPad
    runs-on: ubuntu-latest
    container: ghcr.io/pgaskin/nickeltc:1.0
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build
      run: make all koboroot
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: EfbPad
        path: KoboRoot.tgz
